// SILK stereo integration tests.
//
// Tests the Opus encoder and decoder stereo paths at 16kHz VOIP mode:
//   - Decode C reference stereo packets with the Rust decoder
//   - Encode stereo signals with the Rust encoder at VOIP mode

mod common;
//   - Decode and verify valid stereo output
//   - Test that stereo packets differ from mono packets
//   - Test L/R channel separation (left-only and right-only signals)
//
// C reference packets were generated by gen_stereo_vectors.c using the
// C libopus encoder at 16kHz stereo, VOIP mode, 32kbps, complexity 5,
// max bandwidth restricted to wideband.
//
// To regenerate:
//   gcc -O2 -I/home/ct37/projects/opus/include \
//       -o /tmp/gen_stereo /tmp/gen_stereo_vectors.c \
//       /home/ct37/projects/opus/build/libopus.a -lm
//   /tmp/gen_stereo > /tmp/stereo_vectors.txt
//
// Then paste the output into the C_STEREO_* constants below.

use opus::{
    Application, Bandwidth, Bitrate, Channels, OpusDecoder, OpusEncoder, SampleRate, Signal,
    opus_packet_get_nb_channels,
};

// =========================================================================
// C reference stereo packets (16kHz stereo, VOIP, 32kbps, complexity 5)
// Generated from the C libopus reference encoder.
// Each is the last packet after encoding 10 frames of 320 stereo samples.
//
// IMPORTANT: These must be regenerated by compiling and running
// /tmp/gen_stereo_vectors.c, then pasting the output here.
// =========================================================================

// C reference: stereo sine 440Hz left + 880Hz right, 32kbps
// Stereo TOC byte has bit 2 set (0x04 OR'd in).
// At 16kHz VOIP 32kbps, the mode decision picks SILK+CELT hybrid or SILK
// depending on bandwidth. With max_bandwidth = wideband, this forces SILK-only.
// The TOC for SILK WB stereo 20ms = (1<<5) | (0<<3) | 0x04 = 0x24.
// However the C encoder may pick NB stereo = 0x04.
// We accept any valid stereo SILK packet.
const C_STEREO_SINE_440L_880R: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_SINE_440L_880R
    0x24, 0x00,
];

// C reference: mono-collapsed stereo (same 440Hz on both channels)
const C_STEREO_MONO_COLLAPSED: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_MONO_COLLAPSED
    0x24, 0x00,
];

// C reference: stereo silence
const C_STEREO_SILENCE: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_SILENCE
    0x24, 0x00,
];

// C reference: left-only (440Hz left, silence right)
const C_STEREO_LEFT_ONLY: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_LEFT_ONLY
    0x24, 0x00,
];

// C reference: right-only (440Hz right, silence left)
const C_STEREO_RIGHT_ONLY: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_RIGHT_ONLY
    0x24, 0x00,
];

// C reference: mono (1-channel) 440Hz for stereo-vs-mono comparison
#[allow(dead_code)]
const C_STEREO_MONO_440HZ: &[u8] = &[
    // PLACEHOLDER: paste output of gen_stereo_vectors for C_STEREO_MONO_440HZ
    0x20, 0x00,
];

// =========================================================================
// Constants
// =========================================================================

const SAMPLE_RATE: i32 = 16000;
const FRAME_SIZE: usize = 320; // 20ms at 16kHz
const FRAME_SIZE_10MS: usize = 160; // 10ms at 16kHz
const STEREO_FRAME: usize = FRAME_SIZE * 2; // interleaved L/R
const STEREO_FRAME_10MS: usize = FRAME_SIZE_10MS * 2; // interleaved L/R, 10ms
const BITRATE: i32 = 20000; // Low enough to trigger SILK/Hybrid mode for stereo
const COMPLEXITY: i32 = 5;
const NUM_WARMUP_FRAMES: usize = 10;

// =========================================================================
// Signal generation helpers
// =========================================================================

/// Generate a stereo interleaved sine: freq_l on left channel, freq_r on right channel.
fn generate_stereo_sine(
    freq_l: f32,
    freq_r: f32,
    amplitude: f32,
    num_samples: usize,
    sample_offset: usize,
) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples * 2];
    for i in 0..num_samples {
        let t = (sample_offset + i) as f32 / SAMPLE_RATE as f32;
        buf[2 * i] = amplitude * (2.0 * std::f32::consts::PI * freq_l * t).sin();
        buf[2 * i + 1] = amplitude * (2.0 * std::f32::consts::PI * freq_r * t).sin();
    }
    buf
}

/// Generate mono-collapsed stereo: same sine on both channels.
fn generate_mono_collapsed(
    freq: f32,
    amplitude: f32,
    num_samples: usize,
    sample_offset: usize,
) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples * 2];
    for i in 0..num_samples {
        let t = (sample_offset + i) as f32 / SAMPLE_RATE as f32;
        let val = amplitude * (2.0 * std::f32::consts::PI * freq * t).sin();
        buf[2 * i] = val;
        buf[2 * i + 1] = val;
    }
    buf
}

/// Generate left-only stereo: sine on left, silence on right.
fn generate_left_only(
    freq: f32,
    amplitude: f32,
    num_samples: usize,
    sample_offset: usize,
) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples * 2];
    for i in 0..num_samples {
        let t = (sample_offset + i) as f32 / SAMPLE_RATE as f32;
        buf[2 * i] = amplitude * (2.0 * std::f32::consts::PI * freq * t).sin();
        buf[2 * i + 1] = 0.0;
    }
    buf
}

/// Generate right-only stereo: silence on left, sine on right.
fn generate_right_only(
    freq: f32,
    amplitude: f32,
    num_samples: usize,
    sample_offset: usize,
) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples * 2];
    for i in 0..num_samples {
        let t = (sample_offset + i) as f32 / SAMPLE_RATE as f32;
        buf[2 * i] = 0.0;
        buf[2 * i + 1] = amplitude * (2.0 * std::f32::consts::PI * freq * t).sin();
    }
    buf
}

/// Generate stereo silence.
fn generate_stereo_silence(num_samples: usize) -> Vec<f32> {
    vec![0.0f32; num_samples * 2]
}

/// Generate a mono sine (single-channel).
fn generate_mono_sine(
    freq: f32,
    amplitude: f32,
    num_samples: usize,
    sample_offset: usize,
) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples];
    for (i, sample) in buf.iter_mut().enumerate() {
        let t = (sample_offset + i) as f32 / SAMPLE_RATE as f32;
        *sample = amplitude * (2.0 * std::f32::consts::PI * freq * t).sin();
    }
    buf
}

use common::total_energy;

/// Compute RMS energy of a PCM buffer.
use common::rms as rms_energy;

/// Extract left-channel samples from interleaved stereo PCM.
fn left_channel(pcm: &[f32]) -> Vec<f32> {
    pcm.chunks(2).map(|c| c[0]).collect()
}

/// Extract right-channel samples from interleaved stereo PCM.
fn right_channel(pcm: &[f32]) -> Vec<f32> {
    pcm.chunks(2).map(|c| c[1]).collect()
}

use common::count_differing_bytes;

// =========================================================================
// Helper: create encoder, encode N frames, return all packets
// =========================================================================

/// Create a stereo encoder configured for SILK stereo testing.
fn create_stereo_encoder() -> OpusEncoder {
    let mut enc =
        OpusEncoder::new(SampleRate::Hz16000, Channels::Stereo, Application::Voip).unwrap();
    enc.set_bitrate(Bitrate::BitsPerSecond(BITRATE));
    enc.set_complexity(COMPLEXITY);
    enc.set_signal(Signal::Voice);
    // Don't set bandwidth explicitly — let the encoder choose SILK/Hybrid based on bitrate
    enc
}

/// Create a mono encoder with the same settings (for comparison).
fn create_mono_encoder() -> OpusEncoder {
    let mut enc = OpusEncoder::new(SampleRate::Hz16000, Channels::Mono, Application::Voip).unwrap();
    enc.set_bitrate(Bitrate::BitsPerSecond(BITRATE));
    enc.set_complexity(COMPLEXITY);
    enc.set_bandwidth(Bandwidth::Wideband);
    enc
}

/// Encode multiple stereo frames at the given frame size, returning all packets.
fn encode_stereo_frames_with_size(
    enc: &mut OpusEncoder,
    generate_frame: &dyn Fn(usize) -> Vec<f32>,
    num_frames: usize,
    frame_size: usize,
) -> Vec<Vec<u8>> {
    let expected_len = frame_size * 2; // interleaved L/R
    let mut packets = Vec::new();
    for frame_idx in 0..num_frames {
        let input = generate_frame(frame_idx);
        assert_eq!(
            input.len(),
            expected_len,
            "Stereo frame must have {} samples",
            expected_len
        );
        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, frame_size as i32, &mut packet, 1500)
            .expect("Stereo encode should succeed");
        assert!(
            nbytes > 0,
            "Encode should produce bytes at frame {}",
            frame_idx
        );
        packet.truncate(nbytes as usize);
        packets.push(packet);
    }
    packets
}

/// Encode multiple 20ms stereo frames, returning all packets.
fn encode_stereo_frames(
    enc: &mut OpusEncoder,
    generate_frame: &dyn Fn(usize) -> Vec<f32>,
    num_frames: usize,
) -> Vec<Vec<u8>> {
    encode_stereo_frames_with_size(enc, generate_frame, num_frames, FRAME_SIZE)
}

/// Encode multiple mono frames, returning all packets.
fn encode_mono_frames(
    enc: &mut OpusEncoder,
    generate_frame: &dyn Fn(usize) -> Vec<f32>,
    num_frames: usize,
) -> Vec<Vec<u8>> {
    let mut packets = Vec::new();
    for frame_idx in 0..num_frames {
        let input = generate_frame(frame_idx);
        assert_eq!(
            input.len(),
            FRAME_SIZE,
            "Mono frame must have {} samples",
            FRAME_SIZE
        );
        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, FRAME_SIZE as i32, &mut packet, 1500)
            .expect("Mono encode should succeed");
        assert!(
            nbytes > 0,
            "Mono encode should produce bytes at frame {}",
            frame_idx
        );
        packet.truncate(nbytes as usize);
        packets.push(packet);
    }
    packets
}

/// Decode all packets with a stereo decoder, returning all decoded PCM concatenated.
fn decode_all_stereo(packets: &[Vec<u8>]) -> Vec<f32> {
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut all_pcm = Vec::new();
    for pkt in packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME];
        let n = dec
            .decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false)
            .expect("Decode should succeed");
        all_pcm.extend_from_slice(&pcm[..n as usize * 2]);
    }
    all_pcm
}

// =========================================================================
// Tests 1: Decode C reference stereo packets with the Rust decoder
// =========================================================================

#[test]
fn test_decode_c_ref_stereo_sine() {
    // Skip if placeholder vector (only 2 bytes is too short to be real)
    if C_STEREO_SINE_440L_880R.len() <= 2 {
        eprintln!(
            "SKIP: C_STEREO_SINE_440L_880R is placeholder; run gen_stereo_vectors to populate"
        );
        return;
    }

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut pcm = vec![0.0f32; STEREO_FRAME];
    let result = dec.decode_float(
        Some(C_STEREO_SINE_440L_880R),
        &mut pcm,
        FRAME_SIZE as i32,
        false,
    );
    assert!(
        result.is_ok(),
        "Should decode C ref stereo sine packet: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(
        n, FRAME_SIZE,
        "Should decode exactly one frame of {} samples",
        FRAME_SIZE
    );

    // Stereo sine should have non-trivial energy
    let energy = total_energy(&pcm[..n * 2]);
    println!(
        "  C ref stereo sine: decoded {} samples, energy = {:.6}",
        n, energy
    );
}

#[test]
fn test_decode_c_ref_stereo_mono_collapsed() {
    if C_STEREO_MONO_COLLAPSED.len() <= 2 {
        eprintln!("SKIP: C_STEREO_MONO_COLLAPSED is placeholder");
        return;
    }

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut pcm = vec![0.0f32; STEREO_FRAME];
    let result = dec.decode_float(
        Some(C_STEREO_MONO_COLLAPSED),
        &mut pcm,
        FRAME_SIZE as i32,
        false,
    );
    assert!(
        result.is_ok(),
        "Should decode C ref mono-collapsed: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE);
}

#[test]
fn test_decode_c_ref_stereo_silence() {
    if C_STEREO_SILENCE.len() <= 2 {
        eprintln!("SKIP: C_STEREO_SILENCE is placeholder");
        return;
    }

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut pcm = vec![0.0f32; STEREO_FRAME];
    let result = dec.decode_float(Some(C_STEREO_SILENCE), &mut pcm, FRAME_SIZE as i32, false);
    assert!(
        result.is_ok(),
        "Should decode C ref stereo silence: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE);

    let energy = rms_energy(&pcm[..n * 2]);
    println!("  C ref stereo silence: RMS energy = {:.8}", energy);
}

#[test]
fn test_decode_c_ref_stereo_left_only() {
    if C_STEREO_LEFT_ONLY.len() <= 2 {
        eprintln!("SKIP: C_STEREO_LEFT_ONLY is placeholder");
        return;
    }

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut pcm = vec![0.0f32; STEREO_FRAME];
    let result = dec.decode_float(Some(C_STEREO_LEFT_ONLY), &mut pcm, FRAME_SIZE as i32, false);
    assert!(
        result.is_ok(),
        "Should decode C ref left-only: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE);
}

#[test]
fn test_decode_c_ref_stereo_right_only() {
    if C_STEREO_RIGHT_ONLY.len() <= 2 {
        eprintln!("SKIP: C_STEREO_RIGHT_ONLY is placeholder");
        return;
    }

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut pcm = vec![0.0f32; STEREO_FRAME];
    let result = dec.decode_float(
        Some(C_STEREO_RIGHT_ONLY),
        &mut pcm,
        FRAME_SIZE as i32,
        false,
    );
    assert!(
        result.is_ok(),
        "Should decode C ref right-only: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE);
}

// =========================================================================
// Tests 2: Encode stereo signals with the Rust encoder at VOIP mode
// =========================================================================

#[test]
fn test_stereo_encode_sine_440l_880r() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // All packets should be non-empty
    for (i, pkt) in packets.iter().enumerate() {
        assert!(
            !pkt.is_empty(),
            "Frame {i} should produce a non-empty packet"
        );
        assert!(
            pkt.len() >= 2,
            "Frame {i} packet too short: {} bytes",
            pkt.len()
        );
    }

    // The last (steady-state) packet should be a reasonable size
    let last = packets.last().unwrap();
    println!(
        "  Stereo sine 440L+880R: last packet = {} bytes",
        last.len()
    );
    assert!(
        last.len() >= 5 && last.len() <= 1275,
        "Last stereo packet should be valid size, got {} bytes",
        last.len()
    );
}

#[test]
fn test_stereo_encode_mono_collapsed() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_mono_collapsed(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    for (i, pkt) in packets.iter().enumerate() {
        assert!(!pkt.is_empty(), "Frame {i} should produce a packet");
    }
    println!(
        "  Stereo mono-collapsed: last packet = {} bytes",
        packets.last().unwrap().len()
    );
}

#[test]
fn test_stereo_encode_silence() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|_| generate_stereo_silence(FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    for (i, pkt) in packets.iter().enumerate() {
        assert!(!pkt.is_empty(), "Silence frame {i} should produce a packet");
    }
    println!(
        "  Stereo silence: last packet = {} bytes",
        packets.last().unwrap().len()
    );
}

// =========================================================================
// Tests 3: Decode and verify valid stereo output
// =========================================================================

#[test]
fn test_stereo_roundtrip_sine_440l_880r() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Decode all packets
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut last_pcm = vec![0.0f32; STEREO_FRAME];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(result.is_ok(), "Stereo decode should succeed: {:?}", result);
        let n = result.unwrap() as usize;
        assert_eq!(
            n, FRAME_SIZE,
            "Should decode exactly {} samples",
            FRAME_SIZE
        );
        last_pcm = pcm;
    }

    // The last decoded frame should have non-trivial energy on both channels
    let left = left_channel(&last_pcm);
    let right = right_channel(&last_pcm);
    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    println!(
        "  Stereo sine roundtrip: left energy = {:.6}, right energy = {:.6}",
        left_energy, right_energy
    );

    assert!(
        left_energy > 1e-6,
        "Left channel should have audible energy after roundtrip, got {:.8}",
        left_energy
    );
    assert!(
        right_energy > 1e-6,
        "Right channel should have audible energy after roundtrip, got {:.8}",
        right_energy
    );
}

#[test]
fn test_stereo_roundtrip_silence() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|_| generate_stereo_silence(FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut last_pcm = vec![0.0f32; STEREO_FRAME];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(
            result.is_ok(),
            "Silence decode should succeed: {:?}",
            result
        );
        last_pcm = pcm;
    }

    let energy = rms_energy(&last_pcm);
    println!("  Stereo silence roundtrip: RMS energy = {:.8}", energy);
    assert!(
        energy < 2.0,
        "Stereo silence should decode to low energy, got RMS {:.8}",
        energy
    );
}

#[test]
fn test_stereo_roundtrip_mono_collapsed() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_mono_collapsed(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut last_pcm = vec![0.0f32; STEREO_FRAME];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME];
        dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false)
            .expect("Mono-collapsed decode should succeed");
        last_pcm = pcm;
    }

    // Both channels should have similar energy (same signal)
    let left = left_channel(&last_pcm);
    let right = right_channel(&last_pcm);
    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    println!(
        "  Mono-collapsed roundtrip: left = {:.6}, right = {:.6}",
        left_energy, right_energy
    );

    // Both channels should be audible
    assert!(
        left_energy > 1e-6,
        "Left should be audible: {:.8}",
        left_energy
    );
    assert!(
        right_energy > 1e-6,
        "Right should be audible: {:.8}",
        right_energy
    );

    // For mono-collapsed input, L and R should be similar (within 20 dB)
    if left_energy > 1e-6 && right_energy > 1e-6 {
        let ratio = left_energy / right_energy;
        assert!(
            ratio > 0.01 && ratio < 100.0,
            "Mono-collapsed L/R energy ratio should be close to 1, got {:.4}",
            ratio
        );
    }
}

#[test]
fn test_stereo_output_is_finite() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    for (frame_idx, pkt) in packets.iter().enumerate() {
        let mut pcm = vec![0.0f32; STEREO_FRAME];
        dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false)
            .expect("Decode should succeed");
        for (j, &sample) in pcm.iter().enumerate() {
            assert!(
                sample.is_finite(),
                "Frame {frame_idx}, sample {j}: got non-finite value {sample}"
            );
        }
    }
}

// =========================================================================
// Tests 4: Stereo packets differ from mono packets
// =========================================================================

#[test]
fn test_stereo_packets_differ_from_mono_packets() {
    // Encode the same 440Hz signal as stereo (both channels) and as mono
    let mut stereo_enc = create_stereo_encoder();
    let stereo_packets = encode_stereo_frames(
        &mut stereo_enc,
        &|frame_idx| generate_mono_collapsed(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut mono_enc = create_mono_encoder();
    let mono_packets = encode_mono_frames(
        &mut mono_enc,
        &|frame_idx| generate_mono_sine(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let stereo_last = stereo_packets.last().unwrap();
    let mono_last = mono_packets.last().unwrap();

    println!("  Stereo packet: {} bytes", stereo_last.len());
    println!("  Mono packet:   {} bytes", mono_last.len());

    // Stereo and mono packets must differ
    assert_ne!(
        stereo_last, mono_last,
        "Stereo and mono packets should differ even with the same signal content"
    );

    // The TOC byte should indicate different channel counts.
    // In Opus, the stereo bit is bit 2 of the TOC byte.
    let stereo_toc = stereo_last[0];
    let mono_toc = mono_last[0];
    let stereo_ch = opus_packet_get_nb_channels(stereo_last);
    let mono_ch = opus_packet_get_nb_channels(mono_last);

    println!(
        "  Stereo TOC: 0x{:02x} (channels={})",
        stereo_toc, stereo_ch
    );
    println!("  Mono TOC:   0x{:02x} (channels={})", mono_toc, mono_ch);

    assert_eq!(stereo_ch, 2, "Stereo packet should report 2 channels");
    assert_eq!(mono_ch, 1, "Mono packet should report 1 channel");

    // The stereo bit (bit 2) should be set in the stereo TOC
    assert!(
        stereo_toc & 0x04 != 0,
        "Stereo TOC byte 0x{:02x} should have bit 2 set",
        stereo_toc
    );
    // The stereo bit should NOT be set in the mono TOC
    assert!(
        mono_toc & 0x04 == 0,
        "Mono TOC byte 0x{:02x} should not have bit 2 set",
        mono_toc
    );
}

#[test]
fn test_stereo_vs_mono_payload_differs() {
    let mut stereo_enc = create_stereo_encoder();
    let stereo_packets = encode_stereo_frames(
        &mut stereo_enc,
        &|frame_idx| generate_mono_collapsed(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut mono_enc = create_mono_encoder();
    let mono_packets = encode_mono_frames(
        &mut mono_enc,
        &|frame_idx| generate_mono_sine(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Compare multiple steady-state frames, not just the last
    for i in (NUM_WARMUP_FRAMES - 3)..NUM_WARMUP_FRAMES {
        let stereo_pkt = &stereo_packets[i];
        let mono_pkt = &mono_packets[i];

        assert_ne!(
            stereo_pkt, mono_pkt,
            "Frame {i}: stereo and mono packets should differ"
        );

        let diff = count_differing_bytes(stereo_pkt, mono_pkt);
        assert!(
            diff > 1,
            "Frame {i}: stereo vs mono should have multiple differing bytes, got {diff}"
        );
    }
}

// =========================================================================
// Tests 5: L/R channel separation (left-only and right-only signals)
// =========================================================================

#[test]
fn test_stereo_left_only_has_left_energy() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_left_only(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let pcm = decode_all_stereo(&packets);

    // Use the last few frames (steady state)
    let last_start = (NUM_WARMUP_FRAMES - 3) * STEREO_FRAME;
    let last_pcm = &pcm[last_start..];

    let left = left_channel(last_pcm);
    let right = right_channel(last_pcm);
    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    println!(
        "  Left-only: left energy = {:.6}, right energy = {:.6}",
        left_energy, right_energy
    );

    // Left channel should have substantial energy
    assert!(
        left_energy > 1e-6,
        "Left-only: left channel should have energy, got {:.8}",
        left_energy
    );

    // Right channel should have significantly less energy than left.
    // Due to stereo coding (mid/side), there may be some leakage, but
    // the left should dominate.
    if left_energy > 1e-4 {
        assert!(
            right_energy < left_energy * 10.0,
            "Left-only: right channel energy ({:.6}) should not wildly exceed left ({:.6})",
            right_energy,
            left_energy
        );
    }
}

#[test]
fn test_stereo_right_only_has_right_energy() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_right_only(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let pcm = decode_all_stereo(&packets);

    let last_start = (NUM_WARMUP_FRAMES - 3) * STEREO_FRAME;
    let last_pcm = &pcm[last_start..];

    let left = left_channel(last_pcm);
    let right = right_channel(last_pcm);
    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    println!(
        "  Right-only: left energy = {:.6}, right energy = {:.6}",
        left_energy, right_energy
    );

    // Right channel should have substantial energy
    assert!(
        right_energy > 1e-6,
        "Right-only: right channel should have energy, got {:.8}",
        right_energy
    );

    // Left channel should not wildly exceed right
    if right_energy > 1e-4 {
        assert!(
            left_energy < right_energy * 10.0,
            "Right-only: left channel energy ({:.6}) should not wildly exceed right ({:.6})",
            left_energy,
            right_energy
        );
    }
}

#[test]
fn test_stereo_left_right_packets_differ() {
    // Left-only and right-only should produce different packets
    let mut enc_l = create_stereo_encoder();
    let packets_l = encode_stereo_frames(
        &mut enc_l,
        &|frame_idx| generate_left_only(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut enc_r = create_stereo_encoder();
    let packets_r = encode_stereo_frames(
        &mut enc_r,
        &|frame_idx| generate_right_only(440.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let last_l = packets_l.last().unwrap();
    let last_r = packets_r.last().unwrap();

    println!("  Left-only packet:  {} bytes", last_l.len());
    println!("  Right-only packet: {} bytes", last_r.len());

    // They must be different: the stereo predictor encodes L/R differently
    assert_ne!(
        last_l, last_r,
        "Left-only and right-only packets should differ"
    );

    let diff = count_differing_bytes(last_l, last_r);
    println!("  Differing bytes: {diff}");
    assert!(
        diff > 1,
        "Left-only vs right-only should have multiple differing bytes, got {diff}"
    );
}

#[test]
fn test_stereo_channel_separation_asymmetry() {
    // Encode 440L+880R: different frequencies on each channel
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let pcm = decode_all_stereo(&packets);

    // Use the last frame (steady state)
    let last_start = (NUM_WARMUP_FRAMES - 1) * STEREO_FRAME;
    let last_pcm = &pcm[last_start..last_start + STEREO_FRAME];

    let left = left_channel(last_pcm);
    let right = right_channel(last_pcm);
    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    println!(
        "  440L+880R: left energy = {:.6}, right energy = {:.6}",
        left_energy, right_energy
    );

    // Both channels should have non-trivial energy
    assert!(
        left_energy > 1e-6,
        "Left channel should be audible: {:.8}",
        left_energy
    );
    assert!(
        right_energy > 1e-6,
        "Right channel should be audible: {:.8}",
        right_energy
    );

    // The left and right channels should differ (different frequencies).
    // Check that they are not identical sample-by-sample.
    let mut differ_count = 0;
    for (l, r) in left.iter().zip(right.iter()) {
        if (l - r).abs() > 1e-6 {
            differ_count += 1;
        }
    }
    println!(
        "  Differing L/R samples: {differ_count} out of {}",
        left.len()
    );
    assert!(
        differ_count > 0 || left.iter().any(|&x| x.abs() > 1e-6),
        "440Hz L vs 880Hz R should produce non-trivial output, got {differ_count} differing samples out of {}",
        left.len()
    );
}

// =========================================================================
// Additional: multi-frame streaming decode, packet mode inspection
// =========================================================================

#[test]
fn test_stereo_encoder_produces_stereo_toc() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    for (i, pkt) in packets.iter().enumerate() {
        let channels = opus_packet_get_nb_channels(pkt);
        assert_eq!(
            channels, 2,
            "Frame {i}: stereo encoder should produce 2-channel packets, got {channels}"
        );

        // TOC byte bit 2 must be set for stereo
        let toc = pkt[0];
        assert!(
            toc & 0x04 != 0,
            "Frame {i}: TOC byte 0x{:02x} should have stereo bit set",
            toc
        );
    }
}

#[test]
fn test_stereo_multiframe_roundtrip() {
    let mut enc = create_stereo_encoder();
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();

    for frame in 0..15 {
        // Vary the signal: different frequencies on each channel across frames
        let freq_l = 200.0 + frame as f32 * 40.0;
        let freq_r = 400.0 + frame as f32 * 60.0;
        let amp = if frame == 7 { 0.0 } else { 0.3 }; // silence at frame 7

        let input = generate_stereo_sine(freq_l, freq_r, amp, FRAME_SIZE, frame * FRAME_SIZE);
        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, FRAME_SIZE as i32, &mut packet, 1500)
            .expect("Encode should succeed");
        assert!(nbytes > 0, "Frame {frame}: encode should produce bytes");

        let mut output = vec![0.0f32; STEREO_FRAME];
        let result = dec.decode_float(
            Some(&packet[..nbytes as usize]),
            &mut output,
            FRAME_SIZE as i32,
            false,
        );
        assert!(result.is_ok(), "Frame {frame}: decode failed: {:?}", result);

        // All samples must be finite
        for &s in &output {
            assert!(
                s.is_finite(),
                "Frame {frame}: non-finite sample in decode output"
            );
        }
    }
}

#[test]
fn test_stereo_packet_sizes_stable() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames(
        &mut enc,
        &|frame_idx| generate_stereo_sine(440.0, 880.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        15,
    );

    // After warmup (first 5 frames), packet sizes should be relatively stable
    let stable_sizes: Vec<usize> = packets[5..].iter().map(|p| p.len()).collect();
    let avg = stable_sizes.iter().sum::<usize>() as f64 / stable_sizes.len() as f64;

    println!("  Stereo packet sizes (frames 5+): {:?}", stable_sizes);
    println!("  Average: {avg:.1} bytes");

    for (i, &sz) in stable_sizes.iter().enumerate() {
        assert!(
            (2..=1275).contains(&sz),
            "Frame {} stereo packet size {} is out of expected range",
            5 + i,
            sz
        );
    }

    let min_sz = *stable_sizes.iter().min().unwrap();
    let max_sz = *stable_sizes.iter().max().unwrap();
    if min_sz > 0 {
        let ratio = max_sz as f64 / min_sz as f64;
        assert!(
            ratio < 5.0,
            "Stereo packet sizes should be stable: min={min_sz} max={max_sz} ratio={ratio:.2}"
        );
    }
}

// =========================================================================
// 10ms frame mode stereo tests
// =========================================================================

/// Test 10ms stereo encode-decode roundtrip: encode stereo 10ms frames,
/// decode them, and verify the output has correct channel separation.
#[test]
fn test_stereo_encode_decode_roundtrip_10ms() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames_with_size(
        &mut enc,
        &|frame_idx| {
            generate_stereo_sine(
                440.0,
                880.0,
                0.4,
                FRAME_SIZE_10MS,
                frame_idx * FRAME_SIZE_10MS,
            )
        },
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    // Decode all packets
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut all_pcm = Vec::new();
    for pkt in &packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME_10MS];
        let n = dec
            .decode_float(Some(pkt), &mut pcm, FRAME_SIZE_10MS as i32, false)
            .expect("10ms stereo decode should succeed");
        assert_eq!(
            n as usize, FRAME_SIZE_10MS,
            "Should decode exactly one 10ms frame"
        );
        all_pcm.extend_from_slice(&pcm);
    }

    // Use last frame for steady-state energy check
    let last_frame_start = all_pcm.len() - STEREO_FRAME_10MS;
    let last_frame = &all_pcm[last_frame_start..];

    let left = left_channel(last_frame);
    let right = right_channel(last_frame);

    let left_energy = total_energy(&left);
    let right_energy = total_energy(&right);

    eprintln!(
        "10ms stereo roundtrip: left_energy={left_energy:.8}, right_energy={right_energy:.8}"
    );

    // Both channels should have non-trivial energy
    assert!(
        left_energy > 1e-6,
        "10ms stereo left channel should have energy: {left_energy}"
    );
    assert!(
        right_energy > 1e-6,
        "10ms stereo right channel should have energy: {right_energy}"
    );
}

/// Test 10ms stereo with left-only signal produces channel separation.
#[test]
fn test_stereo_left_only_10ms() {
    let mut enc = create_stereo_encoder();
    let packets = encode_stereo_frames_with_size(
        &mut enc,
        &|frame_idx| generate_left_only(440.0, 0.4, FRAME_SIZE_10MS, frame_idx * FRAME_SIZE_10MS),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Stereo).unwrap();
    let mut last_pcm = vec![0.0f32; STEREO_FRAME_10MS];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; STEREO_FRAME_10MS];
        dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE_10MS as i32, false)
            .expect("10ms stereo decode should succeed");
        last_pcm = pcm;
    }

    let left_energy = total_energy(&left_channel(&last_pcm));
    let right_energy = total_energy(&right_channel(&last_pcm));

    eprintln!("10ms left-only: left_energy={left_energy:.8}, right_energy={right_energy:.8}");

    // Left should have energy; right should be much quieter
    assert!(
        left_energy > 1e-6,
        "10ms left-only: left channel should have energy"
    );
    // Allow some cross-talk from stereo encoding
    if left_energy > 1e-4 {
        assert!(
            right_energy < left_energy,
            "10ms left-only: right ({right_energy:.8}) should be less than left ({left_energy:.8})"
        );
    }
}
