// SILK pitch analysis integration tests.
//
// Tests the SILK encoder's pitch analysis by encoding various signal types
// at 16kHz mono, VOIP mode and verifying that:
//   - The Rust decoder can decode C reference SILK packets without errors

mod common;
//   - The Rust encoder produces valid SILK packets for voiced/unvoiced signals
//   - Voiced signals (200Hz, 300Hz tones) produce different packets than unvoiced (noise)
//   - Encode-decode roundtrips produce audio with correct energy characteristics
//
// C reference packets were generated by gen_pitch_vectors.c using the C libopus
// encoder at 16kHz mono, VOIP mode, complexity 5, 16kbps, with max bandwidth
// restricted to wideband to force SILK-only mode.
//
// To regenerate:
//   gcc -O2 -I/home/ct37/projects/opus/include \
//       -o /tmp/gen_pitch_vectors /tmp/gen_pitch_vectors.c \
//       /home/ct37/projects/opus/build/libopus.a -lm
//   /tmp/gen_pitch_vectors > /tmp/pitch_vectors.txt

use opus::{
    Application, Bandwidth, Bitrate, Channels, Mode, OpusDecoder, OpusEncoder, SampleRate,
    opus_packet_get_bandwidth, opus_packet_get_mode,
};

// =========================================================================
// C reference SILK packets (16kHz mono, VOIP, complexity 5, 16kbps)
// Generated from the C libopus reference encoder.
// Each is the last packet after encoding 10 frames of 20ms (320 samples).
// =========================================================================

// C reference: SILK VOIP 200Hz tone at 16kbps (from c_reference_encode.rs)
// This is a known-good SILK wideband packet for a 200Hz voiced signal.
const C_SILK_200HZ_16K: &[u8] = &[
    0x4b, 0x41, 0x1e, 0x06, 0xe3, 0x79, 0xc5, 0x12, 0xf7, 0xbc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

// C reference: SILK VOIP 200Hz tone at 10kbps
const C_SILK_200HZ_10K: &[u8] = &[
    0x0b, 0x41, 0x11, 0x06, 0xe0, 0xb3, 0x0e, 0xc6, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

// =========================================================================
// Constants
// =========================================================================

const SAMPLE_RATE: i32 = 16000;
const FRAME_SIZE: usize = 320; // 20ms at 16kHz
const FRAME_SIZE_10MS: usize = 160; // 10ms at 16kHz
const BITRATE: i32 = 16000;
const COMPLEXITY: i32 = 5;
const NUM_WARMUP_FRAMES: usize = 10;

// =========================================================================
// Signal generation helpers
// =========================================================================

/// Generate a sine tone at the given frequency and amplitude.
fn generate_tone(freq: f32, amplitude: f32, num_samples: usize, sample_offset: usize) -> Vec<f32> {
    let mut buf = vec![0.0f32; num_samples];
    for (i, sample) in buf.iter_mut().enumerate() {
        *sample = amplitude
            * (2.0 * std::f32::consts::PI * freq * (sample_offset + i) as f32 / SAMPLE_RATE as f32)
                .sin();
    }
    buf
}

/// Generate silence.
fn generate_silence(num_samples: usize) -> Vec<f32> {
    vec![0.0f32; num_samples]
}

/// Generate reproducible white noise using a simple LCG PRNG.
fn generate_noise(amplitude: f32, num_samples: usize, seed: u32) -> Vec<f32> {
    let mut state = seed;
    let mut buf = vec![0.0f32; num_samples];
    for sample in buf.iter_mut() {
        state = state.wrapping_mul(1103515245).wrapping_add(12345);
        let val = ((state >> 16) & 0x7FFF) as f32 / 16384.0 - 1.0;
        *sample = amplitude * val;
    }
    buf
}

/// Compute the RMS energy of a PCM buffer.
use common::rms as rms_energy;

use common::total_energy;

// =========================================================================
// Helper: encode N warmup frames + 1 final frame, return the last packet
// =========================================================================

/// Create an encoder configured for SILK pitch testing.
fn create_silk_encoder() -> OpusEncoder {
    let mut enc = OpusEncoder::new(SampleRate::Hz16000, Channels::Mono, Application::Voip).unwrap();
    enc.set_bitrate(Bitrate::BitsPerSecond(BITRATE));
    enc.set_complexity(COMPLEXITY);
    // Restrict to wideband to force SILK-only mode
    enc.set_bandwidth(Bandwidth::Wideband);
    enc
}

/// Encode multiple frames of signal at the given frame size, returning all packets.
fn encode_frames_with_size(
    enc: &mut OpusEncoder,
    generate_frame: &dyn Fn(usize) -> Vec<f32>,
    num_frames: usize,
    frame_size: usize,
) -> Vec<Vec<u8>> {
    let mut packets = Vec::new();
    for frame_idx in 0..num_frames {
        let input = generate_frame(frame_idx);
        assert_eq!(input.len(), frame_size);
        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, frame_size as i32, &mut packet, 1500)
            .expect("Encode should succeed");
        assert!(nbytes > 0, "Encode should produce bytes");
        packet.truncate(nbytes as usize);
        packets.push(packet);
    }
    packets
}

/// Encode multiple 20ms frames of signal, returning all packets.
fn encode_frames(
    enc: &mut OpusEncoder,
    generate_frame: &dyn Fn(usize) -> Vec<f32>,
    num_frames: usize,
) -> Vec<Vec<u8>> {
    encode_frames_with_size(enc, generate_frame, num_frames, FRAME_SIZE)
}

// =========================================================================
// Tests: Decode C reference SILK packets
// =========================================================================

#[test]
fn test_decode_c_ref_silk_200hz_16k() {
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut pcm = vec![0.0f32; FRAME_SIZE];
    let result = dec.decode_float(Some(C_SILK_200HZ_16K), &mut pcm, FRAME_SIZE as i32, false);
    assert!(
        result.is_ok(),
        "Should decode C ref SILK 200Hz 16kbps packet: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE, "Should decode exactly one frame");
}

#[test]
fn test_decode_c_ref_silk_200hz_10k() {
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut pcm = vec![0.0f32; FRAME_SIZE];
    let result = dec.decode_float(Some(C_SILK_200HZ_10K), &mut pcm, FRAME_SIZE as i32, false);
    assert!(
        result.is_ok(),
        "Should decode C ref SILK 200Hz 10kbps packet: {:?}",
        result
    );
    let n = result.unwrap() as usize;
    assert_eq!(n, FRAME_SIZE, "Should decode exactly one frame");
}

// =========================================================================
// Tests: Rust SILK encode-decode roundtrip for each signal type
// =========================================================================

/// Encode a 200Hz tone for NUM_WARMUP_FRAMES, decode the last packet,
/// and verify the output has meaningful energy.
#[test]
fn test_silk_pitch_200hz_roundtrip() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Decode with a fresh decoder, feeding all packets to build up state
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(result.is_ok(), "Decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy = total_energy(&last_pcm);
    assert!(
        energy > 1e-6,
        "200Hz tone should produce audible output after {NUM_WARMUP_FRAMES} frames, got energy {energy:.8}"
    );
}

/// Encode a 300Hz tone and verify roundtrip.
#[test]
fn test_silk_pitch_300hz_roundtrip() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_tone(300.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(result.is_ok(), "Decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy = total_energy(&last_pcm);
    assert!(
        energy > 1e-6,
        "300Hz tone should produce audible output, got energy {energy:.8}"
    );
}

/// Encode silence and verify roundtrip produces near-zero output.
#[test]
fn test_silk_pitch_silence_roundtrip() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames(
        &mut enc,
        &|_| generate_silence(FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(result.is_ok(), "Decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy_rms = rms_energy(&last_pcm);
    // Silence should decode to very low energy (codec noise floor)
    assert!(
        energy_rms < 0.05,
        "Silence should decode to near-zero energy, got RMS {energy_rms:.8}"
    );
}

/// Encode white noise and verify roundtrip produces audio.
#[test]
fn test_silk_pitch_noise_roundtrip() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_noise(0.3, FRAME_SIZE, 12345 + frame_idx as u32 * 1000),
        NUM_WARMUP_FRAMES,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false);
        assert!(result.is_ok(), "Decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy = total_energy(&last_pcm);
    // Noise should still produce some decoded audio
    assert!(
        energy > 1e-8,
        "Noise should produce some decoded output, got energy {energy:.8}"
    );
}

// =========================================================================
// Tests: Voiced vs unvoiced packet differentiation
// =========================================================================

/// Verify that voiced signals (200Hz, 300Hz tones) produce different packets
/// than unvoiced signals (noise). The SILK encoder should detect periodicity
/// in tonal signals and encode them differently from random noise.
#[test]
fn test_voiced_vs_unvoiced_packets_differ() {
    // Encode 200Hz tone
    let mut enc_200 = create_silk_encoder();
    let packets_200 = encode_frames(
        &mut enc_200,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Encode 300Hz tone
    let mut enc_300 = create_silk_encoder();
    let packets_300 = encode_frames(
        &mut enc_300,
        &|frame_idx| generate_tone(300.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Encode white noise
    let mut enc_noise = create_silk_encoder();
    let packets_noise = encode_frames(
        &mut enc_noise,
        &|frame_idx| generate_noise(0.3, FRAME_SIZE, 12345 + frame_idx as u32 * 1000),
        NUM_WARMUP_FRAMES,
    );

    // Get the last packets (steady state after warmup)
    let pkt_200 = packets_200.last().unwrap();
    let pkt_300 = packets_300.last().unwrap();
    let pkt_noise = packets_noise.last().unwrap();

    // All should be non-empty valid packets
    assert!(!pkt_200.is_empty(), "200Hz packet should be non-empty");
    assert!(!pkt_300.is_empty(), "300Hz packet should be non-empty");
    assert!(!pkt_noise.is_empty(), "Noise packet should be non-empty");

    // The 200Hz and 300Hz packets should differ from each other (different pitch)
    assert_ne!(
        pkt_200, pkt_300,
        "200Hz and 300Hz packets should differ (different pitch periods)"
    );

    // The 200Hz packet should differ from noise
    assert_ne!(
        pkt_200, pkt_noise,
        "200Hz voiced packet should differ from noise packet"
    );

    // The 300Hz packet should differ from noise
    assert_ne!(
        pkt_300, pkt_noise,
        "300Hz voiced packet should differ from noise packet"
    );

    // Compare packet content beyond the TOC byte: voiced signals encode
    // pitch information that noise signals do not. At minimum, the payload
    // bytes should be substantially different.
    let diff_200_noise = count_differing_bytes(pkt_200, pkt_noise);
    let diff_300_noise = count_differing_bytes(pkt_300, pkt_noise);

    // At least some bytes should differ (besides just random variation)
    assert!(
        diff_200_noise > 1,
        "200Hz vs noise should have multiple differing bytes, got {diff_200_noise}"
    );
    assert!(
        diff_300_noise > 1,
        "300Hz vs noise should have multiple differing bytes, got {diff_300_noise}"
    );

    println!("  200Hz packet: {} bytes", pkt_200.len());
    println!("  300Hz packet: {} bytes", pkt_300.len());
    println!("  Noise packet: {} bytes", pkt_noise.len());
    println!("  200Hz vs noise: {diff_200_noise} differing bytes");
    println!("  300Hz vs noise: {diff_300_noise} differing bytes");
}

use common::count_differing_bytes;

/// Verify that two different voiced tones produce packets with different
/// pitch-related content. Since SILK encodes pitch lag information, the
/// 200Hz (period ~80) and 300Hz (period ~53) signals should encode
/// differently in their pitch parameters.
#[test]
fn test_different_pitch_periods_produce_different_packets() {
    let mut enc_200 = create_silk_encoder();
    let packets_200 = encode_frames(
        &mut enc_200,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    let mut enc_300 = create_silk_encoder();
    let packets_300 = encode_frames(
        &mut enc_300,
        &|frame_idx| generate_tone(300.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    // Compare steady-state packets (last few frames)
    for i in (NUM_WARMUP_FRAMES - 3)..NUM_WARMUP_FRAMES {
        let pkt_200 = &packets_200[i];
        let pkt_300 = &packets_300[i];

        // Both should be SILK packets with real content
        assert!(pkt_200.len() > 2, "200Hz frame {i} should have payload");
        assert!(pkt_300.len() > 2, "300Hz frame {i} should have payload");

        // Packets should differ due to different pitch periods
        assert_ne!(
            pkt_200, pkt_300,
            "200Hz and 300Hz frame {i} should produce different SILK packets"
        );
    }
}

// =========================================================================
// Tests: Verify SILK mode is used (packet TOC inspection)
// =========================================================================

/// Verify that the Rust encoder produces SILK-mode packets at 16kHz VOIP
/// with bandwidth restricted to wideband.
#[test]
fn test_encoder_produces_silk_mode_packets() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        NUM_WARMUP_FRAMES,
    );

    for (i, pkt) in packets.iter().enumerate() {
        assert!(!pkt.is_empty(), "Frame {i} should produce a packet");

        let mode = opus_packet_get_mode(pkt);
        assert_eq!(
            mode,
            Mode::SilkOnly,
            "Frame {i}: expected SILK-only mode ({:?}), got {:?}",
            Mode::SilkOnly,
            mode
        );

        let bandwidth = opus_packet_get_bandwidth(pkt);
        // At 16kHz, encoder should use NB or WB SILK
        assert!(
            bandwidth <= Bandwidth::Wideband,
            "Frame {i}: bandwidth {:?} should be <= wideband ({:?})",
            bandwidth,
            Bandwidth::Wideband
        );
    }
}

// =========================================================================
// Tests: Decode energy comparison between signal types
// =========================================================================

/// Verify that decoded energy levels are consistent with the input signal types:
/// - Tonal signals should have substantial energy after roundtrip
/// - Silence should have near-zero energy
/// - Noise should have non-trivial energy (less than tones at same amplitude)
#[test]
fn test_decoded_energy_by_signal_type() {
    // Helper: encode N frames and decode all, return per-frame decoded energies
    fn encode_decode_energies(generate_frame: &dyn Fn(usize) -> Vec<f32>) -> Vec<f64> {
        let mut enc = create_silk_encoder();
        let packets = encode_frames(&mut enc, generate_frame, NUM_WARMUP_FRAMES);

        let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
        let mut energies = Vec::new();
        for pkt in &packets {
            let mut pcm = vec![0.0f32; FRAME_SIZE];
            dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false)
                .expect("Decode should succeed");
            energies.push(total_energy(&pcm));
        }
        energies
    }

    let energies_200hz =
        encode_decode_energies(&|idx| generate_tone(200.0, 0.4, FRAME_SIZE, idx * FRAME_SIZE));
    let energies_300hz =
        encode_decode_energies(&|idx| generate_tone(300.0, 0.4, FRAME_SIZE, idx * FRAME_SIZE));
    let energies_silence = encode_decode_energies(&|_| generate_silence(FRAME_SIZE));
    let energies_noise =
        encode_decode_energies(&|idx| generate_noise(0.3, FRAME_SIZE, 12345 + idx as u32 * 1000));

    // Use the last frame's energy (steady state)
    let e_200 = *energies_200hz.last().unwrap();
    let e_300 = *energies_300hz.last().unwrap();
    let e_silence = *energies_silence.last().unwrap();
    let e_noise = *energies_noise.last().unwrap();

    println!("  Decoded energy (last frame):");
    println!("    200Hz tone: {e_200:.6}");
    println!("    300Hz tone: {e_300:.6}");
    println!("    Silence:    {e_silence:.8}");
    println!("    Noise:      {e_noise:.6}");

    // Tones should have non-trivial energy
    assert!(
        e_200 > 1e-4,
        "200Hz decoded energy should be substantial: {e_200}"
    );
    assert!(
        e_300 > 1e-4,
        "300Hz decoded energy should be substantial: {e_300}"
    );

    // Silence should be very quiet
    assert!(
        e_silence < e_200 * 0.1,
        "Silence energy ({e_silence}) should be much less than 200Hz ({e_200})"
    );
    assert!(
        e_silence < e_300 * 0.25,
        "Silence energy ({e_silence}) should be much less than 300Hz ({e_300})"
    );
}

// =========================================================================
// Tests: Multi-frame streaming decode consistency
// =========================================================================

/// Encode 200Hz for many frames and verify the decoded output stabilizes.
/// The SILK decoder's output should converge after a few warmup frames.
#[test]
fn test_silk_pitch_200hz_stabilizes() {
    let mut enc = create_silk_encoder();
    let total_frames = 20;
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        total_frames,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut frame_energies = Vec::new();
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE as i32, false)
            .expect("Decode should succeed");
        frame_energies.push(total_energy(&pcm));
    }

    // After a few warmup frames, energy should stabilize.
    // Compare energy of frames 10-19 -- they should all be in a similar range.
    let stable_energies = &frame_energies[10..];
    let avg: f64 = stable_energies.iter().sum::<f64>() / stable_energies.len() as f64;
    if avg > 1e-6 {
        for (i, &e) in stable_energies.iter().enumerate() {
            let ratio = e / avg;
            assert!(
                ratio > 0.1 && ratio < 10.0,
                "Frame {} energy {e:.6} deviates too much from average {avg:.6} (ratio {ratio:.3})",
                10 + i
            );
        }
    }
}

/// Encode 300Hz for many frames and verify packet sizes are stable.
#[test]
fn test_silk_pitch_300hz_packet_sizes_stable() {
    let mut enc = create_silk_encoder();
    let total_frames = 15;
    let packets = encode_frames(
        &mut enc,
        &|frame_idx| generate_tone(300.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE),
        total_frames,
    );

    // After warmup, packet sizes should be relatively consistent
    let stable_sizes: Vec<usize> = packets[5..].iter().map(|p| p.len()).collect();
    let avg_size = stable_sizes.iter().sum::<usize>() as f64 / stable_sizes.len() as f64;

    println!("  300Hz packet sizes (frames 5+): {:?}", stable_sizes);
    println!("  Average: {avg_size:.1} bytes");

    // All packets should be a reasonable size for SILK encoding.
    // Note: the Rust encoder may not yet perfectly match the C reference
    // bitrate allocation, so we allow a wide range. The key property is
    // that sizes are consistent across frames (stable encoding).
    for (i, &sz) in stable_sizes.iter().enumerate() {
        assert!(
            (2..=500).contains(&sz),
            "Frame {} packet size {} is out of expected range for SILK encoding",
            5 + i,
            sz
        );
    }
    // Verify sizes are stable: max/min ratio should be reasonable
    let min_sz = *stable_sizes.iter().min().unwrap();
    let max_sz = *stable_sizes.iter().max().unwrap();
    if min_sz > 0 {
        let ratio = max_sz as f64 / min_sz as f64;
        assert!(
            ratio < 3.0,
            "Packet sizes should be stable, but min={min_sz} max={max_sz} ratio={ratio:.2}"
        );
    }
}

// =========================================================================
// Tests: Cross-decode C reference with the Rust decoder
// =========================================================================

/// Decode the C reference 200Hz SILK packet multiple times (simulating
/// a stream) and verify the decoder doesn't accumulate errors.
#[test]
fn test_c_ref_silk_multi_decode_stability() {
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();

    // Feed the same packet multiple times (not ideal but tests decoder stability)
    for i in 0..5 {
        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(Some(C_SILK_200HZ_16K), &mut pcm, FRAME_SIZE as i32, false);
        assert!(
            result.is_ok(),
            "Decode iteration {i} should succeed: {:?}",
            result
        );
        let n = result.unwrap() as usize;
        assert_eq!(
            n, FRAME_SIZE,
            "Should always decode exactly {FRAME_SIZE} samples"
        );

        // Check no NaN or Inf in output
        for (j, &sample) in pcm.iter().enumerate() {
            assert!(
                sample.is_finite(),
                "Decode iteration {i}, sample {j}: got non-finite value {sample}"
            );
        }
    }
}

// =========================================================================
// Tests: Verify the Rust encoder handles edge cases
// =========================================================================

/// Encode a signal that transitions from silence to a tone.
/// The pitch detector should eventually lock on to the tone.
#[test]
fn test_silk_silence_to_tone_transition() {
    let mut enc = create_silk_encoder();
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();

    let total_frames = 15;
    let transition_frame = 5;

    let mut silence_energy_sum = 0.0f64;
    let mut silence_count = 0;
    let mut tone_energy_sum = 0.0f64;
    let mut tone_count = 0;

    for frame_idx in 0..total_frames {
        let input = if frame_idx < transition_frame {
            generate_silence(FRAME_SIZE)
        } else {
            generate_tone(
                200.0,
                0.4,
                FRAME_SIZE,
                (frame_idx - transition_frame) * FRAME_SIZE,
            )
        };

        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, FRAME_SIZE as i32, &mut packet, 1500)
            .expect("Encode should succeed");
        assert!(nbytes > 0);

        let mut pcm = vec![0.0f32; FRAME_SIZE];
        dec.decode_float(
            Some(&packet[..nbytes as usize]),
            &mut pcm,
            FRAME_SIZE as i32,
            false,
        )
        .expect("Decode should succeed");

        let energy = total_energy(&pcm);
        if frame_idx < transition_frame {
            silence_energy_sum += energy;
            silence_count += 1;
        } else if frame_idx >= transition_frame + 3 {
            // After a few frames of tone, energy should be present
            tone_energy_sum += energy;
            tone_count += 1;
        }
    }

    let avg_silence = if silence_count > 0 {
        silence_energy_sum / silence_count as f64
    } else {
        0.0
    };
    let avg_tone = if tone_count > 0 {
        tone_energy_sum / tone_count as f64
    } else {
        0.0
    };

    println!("  Avg silence energy: {avg_silence:.8}");
    println!("  Avg tone energy:    {avg_tone:.8}");

    // After transition, tone frames should have more energy than silence frames
    // (allow for codec startup effects)
    if avg_tone > 1e-6 {
        assert!(
            avg_tone > avg_silence,
            "Tone energy ({avg_tone:.8}) should exceed silence energy ({avg_silence:.8})"
        );
    }
}

/// Encode a signal that transitions from tone to noise.
/// Both should encode successfully with no errors.
#[test]
fn test_silk_tone_to_noise_transition() {
    let mut enc = create_silk_encoder();
    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();

    let total_frames = 15;
    let transition_frame = 7;

    for frame_idx in 0..total_frames {
        let input = if frame_idx < transition_frame {
            generate_tone(300.0, 0.4, FRAME_SIZE, frame_idx * FRAME_SIZE)
        } else {
            generate_noise(0.3, FRAME_SIZE, 54321 + frame_idx as u32 * 999)
        };

        let mut packet = vec![0u8; 1500];
        let nbytes = enc
            .encode_float(&input, FRAME_SIZE as i32, &mut packet, 1500)
            .unwrap_or_else(|_| panic!("Encode should succeed at frame {frame_idx}"));
        assert!(nbytes > 0, "Frame {frame_idx} should produce bytes");

        let mut pcm = vec![0.0f32; FRAME_SIZE];
        let result = dec.decode_float(
            Some(&packet[..nbytes as usize]),
            &mut pcm,
            FRAME_SIZE as i32,
            false,
        );
        assert!(
            result.is_ok(),
            "Decode should succeed at frame {frame_idx}: {:?}",
            result
        );

        // Verify no NaN/Inf
        for &sample in &pcm {
            assert!(sample.is_finite(), "Frame {frame_idx}: non-finite sample");
        }
    }
}

// =========================================================================
// 10ms frame mode tests (2-subframe)
// =========================================================================

#[test]
fn test_silk_pitch_200hz_roundtrip_10ms() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames_with_size(
        &mut enc,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE_10MS, frame_idx * FRAME_SIZE_10MS),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE_10MS];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE_10MS];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE_10MS as i32, false);
        assert!(result.is_ok(), "10ms decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy = total_energy(&last_pcm);
    assert!(
        energy > 1e-6,
        "10ms 200Hz tone should produce audible output after {NUM_WARMUP_FRAMES} frames, got energy {energy:.8}"
    );
}

#[test]
fn test_silk_pitch_silence_roundtrip_10ms() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames_with_size(
        &mut enc,
        &|_| generate_silence(FRAME_SIZE_10MS),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE_10MS];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE_10MS];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE_10MS as i32, false);
        assert!(result.is_ok(), "10ms decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy_rms = rms_energy(&last_pcm);
    assert!(
        energy_rms < 0.05,
        "10ms silence should decode to near-zero energy, got RMS {energy_rms:.8}"
    );
}

#[test]
fn test_silk_pitch_noise_roundtrip_10ms() {
    let mut enc = create_silk_encoder();
    let packets = encode_frames_with_size(
        &mut enc,
        &|frame_idx| generate_noise(0.3, FRAME_SIZE_10MS, 12345 + frame_idx as u32 * 1000),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let mut dec = OpusDecoder::new(SampleRate::Hz16000, Channels::Mono).unwrap();
    let mut last_pcm = vec![0.0f32; FRAME_SIZE_10MS];
    for pkt in &packets {
        let mut pcm = vec![0.0f32; FRAME_SIZE_10MS];
        let result = dec.decode_float(Some(pkt), &mut pcm, FRAME_SIZE_10MS as i32, false);
        assert!(result.is_ok(), "10ms decode should succeed: {:?}", result);
        last_pcm = pcm;
    }

    let energy = total_energy(&last_pcm);
    assert!(
        energy > 1e-8,
        "10ms noise should produce some decoded output, got energy {energy:.8}"
    );
}

#[test]
fn test_voiced_vs_unvoiced_packets_differ_10ms() {
    let mut enc_200 = create_silk_encoder();
    let packets_200 = encode_frames_with_size(
        &mut enc_200,
        &|frame_idx| generate_tone(200.0, 0.4, FRAME_SIZE_10MS, frame_idx * FRAME_SIZE_10MS),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let mut enc_noise = create_silk_encoder();
    let packets_noise = encode_frames_with_size(
        &mut enc_noise,
        &|frame_idx| generate_noise(0.3, FRAME_SIZE_10MS, 12345 + frame_idx as u32 * 1000),
        NUM_WARMUP_FRAMES,
        FRAME_SIZE_10MS,
    );

    let pkt_200 = packets_200.last().unwrap();
    let pkt_noise = packets_noise.last().unwrap();

    assert!(!pkt_200.is_empty(), "10ms 200Hz packet should be non-empty");
    assert!(
        !pkt_noise.is_empty(),
        "10ms noise packet should be non-empty"
    );

    assert_ne!(
        pkt_200, pkt_noise,
        "10ms 200Hz voiced packet should differ from noise packet"
    );

    let diff = count_differing_bytes(pkt_200, pkt_noise);
    assert!(
        diff > 1,
        "10ms 200Hz vs noise should have multiple differing bytes, got {diff}"
    );
}
